[package]
name = "bzfs-manager"
version = "0.1.0"
authors = ["The Noah <thenoahbz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
